name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - name: Pull Sets
        run: node ./dist/data-scrapper.js
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            databases/data.sqlite
            meta.json
          token: "${{ secrets.JPG_ACTION_TOKEN }}"
